### ISSUE TITLE
 I can not get a graph

### ISSUE THREAD

**Issue by Boryslav1** [ableev/Zabbix-in-Telegram#115]
Zdrastvujte.
Help me please.
I do everything according to instructions, but I can not get a graph.

In the telegraph the following error:
Zabbix user could not get graph (probably has no rights to get data from host), check script manually, see ...

And in the console:
Traceback (most recent last call last):
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 886, in <module>
    main ()
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 840, in main
    settings ["zbxtg_image_height"])
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 293, in graph_get
    title = requests.utils.quote (title)
  File "/usr/lib/python2.7/urllib.py", line 1286, in quote
    raise TypeError ('None object can not be quoted')
TypeError: None object can not be quoted

It seems I've tried all the settings.
What am I doing wrong. Thank you.

**Comment by ableev** [comment]
@Boryslav1 show input, not only output

**Comment by Alien-hide** [comment]
"Login to Zabbix web UI has failed (web url, user or password are incorrect), unable to send graphs check manually"

Данное сообщение появляется при использовании таких настроек:

> 

# -*- coding: utf-8 -*-

tg_key = "key без приставки bot"

zbx_tg_prefix = "zbxtg"  # variable for separating text from script info
zbx_tg_tmp_dir = "/var/tmp/" + zbx_tg_prefix  # directory for saving caches, uids, cookies, etc.
zbx_tg_signature = False

zbx_tg_update_messages = True
zbx_tg_matches = {
    "problem": "PROBLEM: ",
    "ok": "OK: "
}

zbx_server = "http://парам-пам-пам/"  # zabbix server full url (если использую ) http://парам-пам-пам/zabbix то zabbix ругается что не могу отправить
zbx_api_user = "пам"
zbx_api_pass = "пам-парам"
zbx_api_verify = False  # True - do not ignore self signed certificates, False - ignore

zbx_basic_auth = False
zbx_basic_auth_user = "zabbix"
zbx_basic_auth_pass = "zabbix"

proxy_to_zbx = None
proxy_to_tg = None

#proxy_to_zbx = "proxy.local:3128"
#proxy_to_tg = "proxy.local:3128"

google_maps_api_key = None  # get your key, see https://developers.google.com/maps/documentation/geocoding/intro

zbx_tg_daemon_enabled = False
zbx_tg_daemon_wl_ids = [6931850, ]
zbx_tg_daemon_wl_u = ["ableev", ]

zbx_db_host = "localhost"
zbx_db_database = "zabbix"
zbx_db_user = "zbxtg"
zbx_db_password = "zbxtg"


emoji_map = {
 "OK": "✅",
 "Not classified": "❕",
 "Information": "ℹ",
 "Warning": "⚠",
 "Average": "❗",
 "High": "❌",
 "Disaster": "🔥"
}

**Comment by Alien-hide** [comment]
если указываю host/zabbix  то в zabbix'e ошибка:
zbxtg.py: probably the server in your config file has not full URL (for example 'http://host/zabbix' instead of 'http://host/zabbix/zabbix')
Traceback (most recent call last):
File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 888, in <module>
main()
File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 842, in main
settings["zbxtg_image_height"])
File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 295, in graph_get
title = requests.utils.quote(title)
File "/usr/lib64/python2.7/urllib.py", line 1269, in quote
raise TypeError('None object cannot be quoted')
TypeError: None object cannot be quoted

и в телеграм сыплется 3 одинаковых сообщения без графиков, ну что и понятно потому что 
probably the server in your config file has not full URL возникает если не получили токен api насколько я понял 

Запрос такого вида возвращает правильный ответ: 
curl -d '{"jsonrpc": "2.0","method": "user.login","params": {"user": "Admin","password":"zabbix"},"id": 1, "auth": null}' -H "Content-Type: application/json" -X POST http://host/zabbix/api_jsonrpc.php

{"jsonrpc":"2.0","result":"8628c35cb94bdc1c3fa58d69ef6589d8","id":1}

Эта же ошибка по коду мне не понятна: Login to Zabbix web UI has failed

**Comment by Alien-hide** [comment]
забрался дело было в
в отсутствии нужных полей в теле алерта 
zbxtg;title:{HOST.HOST} - {TRIGGER.NAME}
zbxtg;itemid:{ITEM.ID1}

**Comment by hertell** [comment]
pretty useless solution for people not knowing what you are writing..

**Comment by Varrkan82** [comment]
The solution is very simple. Just follow the manual!

**Comment by ableev** [comment]
@hertell you mean russian? Or what? 
The last answer makes point: some users just don't read the README. :)

**Comment by hertell** [comment]
Yep, it was about russian.. I the characters are pure mystery to me :-) RTFM is a common problem even for me ;-)
