### ISSUE TITLE
markdown

### ISSUE THREAD

**Issue by Smiley-k** [ableev/Zabbix-in-Telegram#69]
Перестали отправляться сообщения из zabbix, в интерфейсе отображается что сообщение было отправлено, если убрать ключ **--markdown** сообщения начинают отправляться.

![2017-04-09 16 03 17](https://cloud.githubusercontent.com/assets/11009787/24837497/5b26c8b2-1d3e-11e7-9fd1-2279a721ce2c.png)

**Comment by Smiley-k** [comment]
Такая проблема только у меня или я один использую этот ключ ?

**Comment by ableev** [comment]
@Smiley-k could you please share full text of an action? Including special symbols.

**Comment by yuriimuratov** [comment]
I think I have same issue. I am sure that the problem comes from underscore or another markdown characters not closed properly.

```
./zbxtg.py "@******" "*test*" "testing_underscore" --debug --markdown --disable_web_page_preview
zbxtg.py: {u'ok': True, u'result': {u'username': u'******', u'first_name': u'BOT', u'is_bot': True, u'id': *******}}
zbxtg.py: Cache file with uids: /tmp/zbxtg/uids.txt
zbxtg.py: 'disable_web_page_preview' option has been enabled
zbxtg.py: Telegram uid of private '*****': ******

zbxtg.py: Trying to /sendMessage:
zbxtg.py: https://api.telegram.org/******/sendMessage
zbxtg.py: post params: {'text': '*test*\ntesting_underscore', 'disable_notification': False, 'parse_mode': 'Markdown', 'chat_id': '******\n', 'disable_web_page_preview': True}
zbxtg.py: {u'error_code': 400, u'ok': False, u'description': u"Bad Request: can't parse entities in message text: Can't find end of the entity starting at byte offset 14"}
```
If the markdown parser finds an opening markdown symbol without the corresponding closing one, it throws an error. So probably, you have an odd number of * or _ in your text.

But make attention  there is no error message in Zabbix report. Error message must be properly returned into frontend web-interface but Zabbix tells that the messages are successfully sent.

**Comment by ableev** [comment]
Fixed in `dev` branch in #83
